//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18034
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyPhotoSharing.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyPhotoSharing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} was disconnected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CHAT_CLOSE {
            get {
                return ResourceManager.GetString("CHAT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [from SPS]  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CHAT_HEAD {
            get {
                return ResourceManager.GetString("CHAT_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perhaps {0} wants to sharing photos to you. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CHAT_OPEN {
            get {
                return ResourceManager.GetString("CHAT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perhaps {0} posts a new photo &apos;{1}&apos; for you. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CHAT_SENT_PHOTO {
            get {
                return ResourceManager.GetString("CHAT_SENT_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skype can&apos;t recieve a file from user&apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_FILE_CANT_RECIEVE {
            get {
                return ResourceManager.GetString("ERROR_FILE_CANT_RECIEVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file &apos;{0}&apos; can&apos;t send to user&apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_FILE_CANT_SEND {
            get {
                return ResourceManager.GetString("ERROR_FILE_CANT_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can never recognize the file &apos;{0}&apos; as photo. It&apos;s broken or not a photo data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_FILE_NOT_PHOTO {
            get {
                return ResourceManager.GetString("ERROR_FILE_NOT_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File transfer with {0} was already disconnected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_FILE_TRANSFER_DISCONNECT {
            get {
                return ResourceManager.GetString("ERROR_FILE_TRANSFER_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File {1} transfer with {0} was timeout failed.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_FILE_TRANSFER_TIMEOUT {
            get {
                return ResourceManager.GetString("ERROR_FILE_TRANSFER_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t connect to Skype. What&apos;s up? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_SKYPE_DISABLE {
            get {
                return ResourceManager.GetString("ERROR_SKYPE_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oops!!: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE_ERROR_OCCURRED_CAPTION {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_OCCURRED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add photo sharing user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TIP_ADD_USER {
            get {
                return ResourceManager.GetString("TIP_ADD_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close this photo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TIP_CLOSE_PHOTO {
            get {
                return ResourceManager.GetString("TIP_CLOSE_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save to local に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TIP_SAVE {
            get {
                return ResourceManager.GetString("TIP_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale just fit size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TIP_SCALE_FIT {
            get {
                return ResourceManager.GetString("TIP_SCALE_FIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to original size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TIP_SCALE_ORIGIN {
            get {
                return ResourceManager.GetString("TIP_SCALE_ORIGIN", resourceCulture);
            }
        }
    }
}
